# Generated by Django 2.2 on 2020-01-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='discription',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
