# Generated by Django 2.2 on 2019-12-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='startDate',
            field=models.DateField(),
        ),
    ]
