# Generated by Django 2.2 on 2019-12-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evolution', '0003_auto_20191215_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='player',
        ),
    ]
