# Generated by Django 2.2 on 2019-12-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolution', '0004_remove_phase_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
