# Generated by Django 2.2 on 2019-12-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolution', '0005_auto_20191215_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
