# Generated by Django 2.2 on 2019-12-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolution', '0006_theme_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
