# Generated by Django 2.2 on 2019-12-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='adddate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(default='No description', max_length=1500),
        ),
        migrations.AddField(
            model_name='job',
            name='shortname',
            field=models.CharField(default='', max_length=10),
        ),
    ]
