# Generated by Django 3.1 on 2020-09-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='externalurl',
            field=models.CharField(default='Internal deploy', max_length=200, null=True),
        ),
    ]
