# Generated by Django 3.1 on 2020-09-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_externalurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='isexrernalurl',
            field=models.BooleanField(default=False),
        ),
    ]
